version: '3.8'
services:
  app:
    image: jester
    build:
      context: ./
      target: dev
      dockerfile: Dockerfile
    volumes:
      - type: bind
      - source: .
      - target: app
    ports:
      - "3000:3000"